import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Corredores } from 'src/app/interface/corredores';

@Component({
  selector: 'app-detalle-corredor',
  templateUrl: './detalle-corredor.page.html',
  styleUrls: ['./detalle-corredor.page.scss'],
})
export class DetalleCorredorPage implements OnInit {
  nombreCorredor?: string | null;
  corredores = [
    { nombre: 'Max', apellido: 'Verstappen', escuderia: 'RedBull', imagen: 'assets/corredores/verstappen.jpg', descripcion: 'Max Verstappen, a los 17 años, hizo historia en la F1 como el piloto más joven en competir. Con un estilo agresivo y audaz, ganó su primera carrera a los 18 años y se destacó por sus impresionantes actuaciones, como la remontada en Brasil. Aunque su actitud a veces le ha generado conflictos, su madurez ha crecido junto con sus victorias, incluyendo campeonatos consecutivos en 2021, 2022 y 2023. Hijo del ex piloto Jos Verstappen y de la kartista Sophie Kumpen, Verstappen, ahora con 24 años, es el primer campeón mundial de los Países Bajos y se perfila como una estrella con un futuro prometedor.' },
    { nombre: 'Sergio', apellido: 'Perez', escuderia: 'RedBull', imagen: 'assets/corredores/perez.jpg', descripcion: 'Sergio Pérez es conocido en la F1 por su estilo de conducción enérgico y estratégico. Se destaca tanto por su habilidad en la pista como por su maestría en la gestión de neumáticos y la estrategia. Después de su paso por equipos como Sauber, McLaren, Force India y Racing Point, ha acumulado más puntos que cualquier otro mexicano en la historia de la F1. Su victoria en Sakhir 2020 lo igualó con Pedro Rodríguez y le aseguró un lugar en Red Bull. Aunque su lucha por el título puede verse opacada por Max Verstappen, Pérez sigue compitiendo con pasión y dedicación.' },
    { nombre: 'Lando', apellido: 'Norris', escuderia: 'Mclaren', imagen: 'assets/corredores/norris.jpg', descripcion: 'Lando Norris, a pesar de no tener el nombre de Lando Calrissian, demuestra un estilo y espíritu de lucha notables en la F1. Debutó con McLaren en 2019, impresionando con su rendimiento en clasificación y carreras. En su primera temporada, superó a Carlos Sainz y anotó puntos regularmente. Su primer podio llegó en 2020, seguido de sólidas actuaciones en 2021, incluyendo una cercana victoria en Rusia. Fuera de la pista, Norris combina su talento en la carrera con habilidades artísticas, diseñando y pintando su propia ropa de competición. McLaren confía en su promesa para alcanzar el éxito.' },
    { nombre: 'Oscar', apellido: 'Piastri', escuderia: 'Mclaren', imagen: 'assets/corredores/piastri.jpg', descripcion: 'Oscar Piastri, originario de Melbourne, soñaba con la F1 desde joven, inspirado por el Gran Premio de Australia en su ciudad. Para alcanzar ese sueño, se mudó a Europa, siguiendo el camino de otros australianos como Mark Webber y Daniel Ricciardo. Piastri usó su éxito en karting australiano para avanzar en monoplazas, destacando en F4 UAE y luego ganando campeonatos en Fórmula 4, Renault, Fórmula 3 y Fórmula 2. Su talento le aseguró un lugar en la F1 en 2023, con McLaren y Alpine compitiendo por él. En su temporada de debut, logró dos podios y demostró su potencial.' },
    { nombre: 'Charles', apellido: 'Leclerc', escuderia: 'Ferrari', imagen: 'assets/corredores/leclerc.jpg', descripcion: 'Nacido en Mónaco, Charles Leclerc llegó a la F1 en 2018 con altas expectativas tras ganar títulos en GP3 y Fórmula 2. Su habilidad para manejar la presión y su desempeño impresionante le aseguraron un lugar en Ferrari, donde rápidamente se destacó, superando a Sebastian Vettel y logrando victorias en Spa y Monza. A pesar de las dificultades de Ferrari en 2020 y 2021, Leclerc demostró su capacidad en 2022 con tres victorias y 11 podios, siendo el principal rival de Max Verstappen. Fuera de la pista, Leclerc corre en honor a su difunto padre y a su amigo y mentor, Jules Bianchi.' },
    { nombre: 'Carlos', apellido: 'Sainz', escuderia: 'Ferrari', imagen: 'assets/corredores/saiz.jpg', descripcion: 'Carlos Sainz, conocido como "Chilli," ha mostrado un gran espíritu de lucha desde su debut en F1 con Toro Rosso en 2015. Conocido por su habilidad para llevar el coche al límite y sumar puntos de manera inteligente, Sainz también mantiene una actitud tranquila fuera de la pista. Hijo del campeón de rally Carlos Sainz, ha seguido una carrera destacada, primero en McLaren y luego en Ferrari, donde ha reemplazado a Sebastian Vettel. A pesar de la presión de estar a la sombra de grandes nombres, ha logrado una victoria en cada una de sus dos temporadas con Ferrari.' },
    { nombre: 'Lewis', apellido: 'Hamilton', escuderia: 'Mercedes', imagen: 'assets/corredores/hamilton.jpg', descripcion: 'Lewis Hamilton, con la frase "Still I Rise" en su casco y tatuajes, ha superado expectativas desde su impresionante debut en 2007. Ha batido récords de pole positions, superado a Michael Schumacher en victorias y igualado sus siete títulos mundiales. Considerado uno de los mejores de todos los tiempos, Hamilton ha alcanzado el éxito manteniendo su autenticidad y desafiando los estereotipos. Respetado por sus compañeros, es conocido por su velocidad implacable y su determinación en la pista.' },
    { nombre: 'George', apellido: 'Russell', escuderia: 'Mercedes', imagen: 'assets/corredores/russell.jpg', descripcion: 'George Russell, conocido por su lema "En caso de duda, ve a toda velocidad," ha demostrado su velocidad y tenacidad desde su debut en F1. Superó a Robert Kubica en su temporada de novato con Williams, colocó al equipo en el podio en 2021 y ganó su primera carrera con Mercedes en 2022. Su carrera comenzó con títulos en GP3 y Fórmula 2, y fue fichado por Mercedes en 2017. Su destacada actuación sustituyendo a Lewis Hamilton en 2020 le valió elogios y una victoria en Brasil en 2022. Aunque la temporada 2023 fue más desafiante, Russell sigue siendo un competidor tenaz con grandes expectativas para el futuro.' },
    { nombre: 'Fernando', apellido: 'Alonso', escuderia: 'Aston Martin', imagen: 'assets/corredores/alonso.jpg', descripcion: 'Michael Schumacher fue el dominante de la F1 a principios de los 2000, pero Fernando Alonso, con su feroz competitividad, emergió como su principal rival. Conocido por su velocidad, estrategia y técnica impecable, Alonso fue el piloto más joven en lograr la pole, ganar una carrera y conseguir dos títulos mundiales con Renault. Aunque no pudo replicar ese éxito en McLaren y Ferrari, regresó a la F1 en 2021 con Alpine tras dos años de ausencia y victorias en Le Mans. Ahora en Aston Martin, Alonso busca retomar el camino hacia el triunfo y cerrar asuntos pendientes con la F1.' },
    { nombre: 'Lance', apellido: 'Stroll', escuderia: 'Aston Martin', imagen: 'assets/corredores/stroll.jpg', descripcion: 'Lance Stroll, debutando en la F1 con solo 18 años en 2017 con Williams, demostró su talento al subirse al podio en Bakú y lograr la pole en Monza, convirtiéndose en el piloto más joven en ambos casos. Hijo de un adinerado empresario, Stroll disfruta del lujo, pero valora aún más los éxitos en pista. Tras la compra de Force India por su padre, el equipo se transformó en Aston Martin, donde Stroll ha continuado su ascenso, destacando con una pole y dos podios en 2020. Con un futuro prometedor, Stroll sigue mostrando su potencial, incluso bajo la lluvia.' },
    { nombre: 'Yuki', apellido: 'Tsunoda', escuderia: 'RB', imagen: 'assets/corredores/tsunoda.jpg', descripcion: 'Yuki Tsunoda, el piloto japonés de Red Bull, podría ser el primero de su país en ganar un Gran Premio. Su ascenso a la F1 fue sorprendentemente rápido, pasando de la F4 japonesa a AlphaTauri en poco más de tres años. Tras una destacada campaña en F2, Tsunoda ha demostrado tener la velocidad y la experiencia necesarias para competir al más alto nivel. Aunque su adaptación a la F1 ha sido gradual, su potencial sigue siendo alto, y con un futuro prometedor en Red Bull, podría estar en la lucha por los primeros puestos.' },
    { nombre: 'Daniel', apellido: 'Ricciardo', escuderia: 'RB', imagen: 'assets/corredores/ricciardo.jpg', descripcion: 'El autodenominado "Tejón de miel", Daniel Ricciardo, combina una personalidad relajada con una feroz competitividad en la pista. Conocido por su habilidad para adelantar y su icónico Shoey de champán, Ricciardo ha demostrado ser un corredor de élite, especialmente durante su tiempo en Red Bull. Aunque su paso por Renault y McLaren presentó desafíos, regresó a la Fórmula 1 con Red Bull y AlphaTauri. A pesar de un breve retiro debido a una fractura, Ricciardo mantiene su objetivo de regresar al equipo principal y seguir deslumbrando con su velocidad y carisma.' },
    { nombre: 'Nico', apellido: 'Hulkenberg', escuderia: 'Haas', imagen: 'assets/corredores/Hulkenberg.jpg', descripcion: 'Nico Hülkenberg, el "Hulk" de la F1, ha demostrado una notable habilidad y consistencia a lo largo de su carrera, destacándose en equipos como Williams, Force India, Sauber, Renault, Racing Point, Aston Martin y Haas. Su primera pole position en Brasil en 2010 y la victoria en las 24 Horas de Le Mans en 2015 subrayan su talento y versatilidad. A pesar de su historial sin podios en la F1 y los desafíos que ha enfrentado, Hülkenberg mantiene un enfoque realista y un humor característico. Su regreso a tiempo completo con Haas ofrece una nueva oportunidad para mostrar su capacidad y finalmente alcanzar el podio.' },
    { nombre: 'Kevin', apellido: 'Magnussen', escuderia: 'Haas', imagen: 'assets/corredores/magnussen.jpg', descripcion: 'Kevin Magnussen, el "llanero solitario" de la Fórmula 1, sigue el legado de su padre, Jan, con una pasión indomable por las carreras. Desde su impresionante debut con McLaren, logrando un podio en el Gran Premio de Australia de 2014, hasta su regreso a Haas y su primera pole position en Brasil en 2022, Magnussen ha demostrado un enfoque competitivo y una habilidad destacada. A pesar de su reputación de "chico malo" en la pista, fuera del auto es conocido por su actitud relajada y amigable, siempre enfocado en su amor por el deporte.' },
    { nombre: 'Pierre', apellido: 'Gasly', escuderia: 'Alpine', imagen: 'assets/corredores/gasly.jpg', descripcion: 'Pierre Gasly ha demostrado una habilidad notable para aprovechar las oportunidades en la Fórmula 1. Desde su debut en Malasia en 2017, su carrera ha sido una montaña rusa de éxitos y desafíos. Tras un ascenso rápido a Red Bull, la temporada 2019 no fue fácil para él, pero su regreso a Toro Rosso (luego AlphaTauri) mostró su capacidad para recuperarse y destacar, culminando en una victoria en Monza en 2020. Su desempeño en 2021 solidificó su posición como un piloto de gran talento. Con su traslado a Alpine en 2023, Gasly busca revitalizar su carrera y alcanzar nuevas alturas en la F1.' },
    { nombre: 'Esteban', apellido: 'Ocon', escuderia: 'Alpine', imagen: 'assets/corredores/ocon.jpg', descripcion: 'Esteban Ocon es un ejemplo inspirador de perseverancia y sacrificio en la Fórmula 1. Desde sus humildes comienzos hasta alcanzar la cima del automovilismo, su trayectoria ha sido marcada por el esfuerzo y la dedicación de su familia. Su victoria en la F1, después de superar desafíos y períodos de incertidumbre, subraya su talento y resiliencia. Ocon ha demostrado que, con determinación y una mentalidad fuerte, es posible convertir las adversidades en éxitos y seguir ascendiendo en el competitivo mundo de la Fórmula 1.' },
    { nombre: 'Alexander', apellido: 'Albon', escuderia: 'Williams', imagen: 'assets/corredores/albon.jpg', descripcion: 'Alexander Albon, nacido en Londres y corriendo bajo la bandera tailandesa, comenzó su carrera en F1 con Toro Rosso en 2019 antes de ser promovido a Red Bull. A pesar de un 2020 difícil, donde fue reemplazado, se mantuvo como piloto de pruebas y volvió a la parrilla con Williams en 2022. Conocido por su habilidad para adelantar y su actitud positiva, Albon sigue buscando aprovechar al máximo su segunda oportunidad en la F1.' },
    { nombre: 'Logan', apellido: 'Sargeant', escuderia: 'Williams', imagen: 'assets/corredores/sargeant.jpg', descripcion: 'Logan Sargeant, el primer piloto estadounidense en F1 en casi ocho años, debutó en la temporada 2023 con Williams. Tras una exitosa carrera en karting y varios campeonatos menores, Sargeant demostró su velocidad y potencial al terminar en los primeros lugares en F4, F3 y F2, ganando su lugar en la parrilla de F1. Aunque su primera temporada le dio solo un punto, con tres carreras en EE.UU. en el calendario, Sargeant cuenta con un sólido apoyo local.' },
    { nombre: 'Valtteri', apellido: 'Bottas', escuderia: 'Kick Sauber', imagen: 'assets/corredores/bottas.jpg', descripcion: 'Valtteri Bottas, con formación en Finlandia, debutó en F1 con Williams en 2013. Se unió a Mercedes, destacando con pole positions y victorias. Aunque enfrentó desafíos en 2018 y vio una disminución en victorias en 2020-2021, comenzó una nueva etapa con Alfa Romeo (ahora Kick Sauber) en 2022, liderando junto a Zhou Guanyu.' },
    { nombre: 'Zhou', apellido: 'Guanyu', escuderia: 'Kick Sauber', imagen: 'assets/corredores/zhou.jpg', descripcion: 'Zhou Guanyu se convirtió en el primer piloto chino titular de F1 en 2022 con Alfa Romeo (ahora Kick Sauber). Inspirado por Fernando Alonso desde joven, Zhou se mudó a Inglaterra a los 12 años para perseguir su sueño. Destacó en la Fórmula 4 y la Fórmula 2, lo que le valió una oportunidad en F1 con Alfa Romeo, junto a Valtteri Bottas.' }
  ];
  
  corredor?: Corredores; 

  constructor(private activateRoute: ActivatedRoute) { }

  ngOnInit() {
     this.nombreCorredor = this.activateRoute.snapshot.paramMap.get('nombre');
    this.obtenerDetalleCorredor();
  }
  
  obtenerDetalleCorredor() {
    if (this.nombreCorredor) {
      this.corredor = this.corredores.find(corredor => corredor.nombre === this.nombreCorredor);
    }
  }
}
